# ==============================================================================
#  open-ortho ovena v0.4.0
# ==============================================================================
#  WARNING: DO NOT MAKE ANY MODIFICATIONS TO THIS FILE!
#  This file is maintained by the package maintainer and will be overwritten 
#  at the next update.
# ==============================================================================
#
services:
  nginx-reverse-proxy:
    image: lscr.io/linuxserver/nginx
    container_name: $<PROJECT_NAME>-nginx
    environment: 
      PUID: "1000"
      PGID: "1000"
      TZ: "Europe/Rome"
    volumes: [
      "$<OVENA_CONFIG>/nginx/config:/config"
    ]
    restart: unless-stopped
    ports: [
      "${ORTHANC_IP}80:80",
      "${ORTHANC_IP}443:443",
    ]
  orthanc:
    image: osimis/orthanc:23.6.0
    container_name: $<PROJECT_NAME>-orthanc
    depends_on: [$<DATABASE_DOCKER_IMAGE>]
    restart: unless-stopped
    ports: [
      "${ORTHANC_IP}104:4242"
      ]
    volumes: [
      /var/lib/docker/volumes/ovena/orthanc/data:/var/lib/orthanc/db:Z,
      "$<OVENA_CONFIG>/orthanc/:/etc/orthanc/:ro"
      ]
    environment: 
      VERBOSE_ENABLED: "false"
      VERBOSE_STARTUP: "false"
      OSIMIS_WEB_VIEWER1_PLUGIN_ENABLED: "true"
      STONE_WEB_VIEWER_PLUGIN_ENABLED: "true"
      DICOM_WEB_PLUGIN_ENABLED: "true"
      ORTHANC__STONE_WEB_VIEWER__DATE_FORMAT: "YYYY-MM-DD"


  $<DATABASE_DOCKER_IMAGE>:
    image: postgres:15
    container_name: $<PROJECT_NAME>-postgres
    restart: unless-stopped
    volumes: [
      "/var/lib/docker/volumes/ovena/$<DATABASE_DOCKER_IMAGE>:/var/lib/postgresql/data",
      "/var/lib/docker/volumes/ovena/$<DATABASE_DOCKER_IMAGE>-backup:/mnt/backup"
      ]
    environment:
      POSTGRES_USER: "$<DATABASE_USERNAME>"
      POSTGRES_PASSWORD: "postgres"
